### ISSUE TITLE
BLTouch and Breakout board voltage issue

### ISSUE THREAD

**Issue by jrbenito** [ginge/Ender6#2]
The Ender 6 breakout has compromised in cabling by sharing ground lines and not providing 5v to Antclabs BLTouch.

The Antclabs BLTouch works with 3v3 logic but requires 5V to work. If supplied with 3v3 it will work but may present intermittent fails or malfunctioning. Creality bord 4.3.1 has a dedicated connector for BLTouch where a 5v pin is available to supply Vcc to BLTouch, however, it is not wired to the breakout board.

In order to properly function, wire Vcc (and possibly GND) direct to the mainboard instead of using breakout board. Signal and PWM can still be sourced from breakout board for easy maintenance.

**Comment by ginge** [comment]
Interesting, however this is not the official ender repo, just some firmware i'm working on. Sadly I don't know the appropriate channel for you to report this.
