### ISSUE TITLE
Ender6 not work LCD

### ISSUE THREAD

**Issue by coderssociety** [ginge/Ender6#3]
Since I upgraded my Ender6 printer, I need to update the configuration.h file. But the lcd screen does not work in all marlin versions.  
Lines I need to change in configuration.h ;
#define TEMP_SENSOR_0 5
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 400, 690 }
#define DEFAULT_MAX_FEEDRATE          { 500, 500, 10, 120 }
    #define MAX_JERK_EDIT_VALUES { 20, 20, 0.6, 5 }

and settings required for creality cr touch

Is there a version of marlin that the stock LCD screen works with? Can you help me?

**Comment by ginge** [comment]
No idea. This repo is really buggy still. I wouldn't consider using it for your purposes.
